# Site setings
name: 'Kris Bolton'
description: 'The personal website of Kris Bolton, Cyber Security Research Student.'
meta_description: 'Cyber Security.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: 
disqus:
mailchimp_url: 'https://krisbolton.us12.list-manage.com/subscribe/post?u=f493e5bbda4cf62b8809b4b61&amp;id=798a6931cc'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-781038-17


# Author
author:
  name: 'Kris Bolton'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Kris Bolton. I'm a Cyber Security research student (MSc) and Machine Learning enthusiast from the United Kingdom. It’s nice to meet you."
  bio: 'Kris is a Cyber Security masters student with a background in Computer Science (Software Engineering), his research focus is Critical National Infrastructure Defense and Advanced Persistent Threats.'

# Contact form setings
email: krisbolton@gmail.com
contact_page_description:

# Social links
twitter: 'krisbolton'
facebook:
github: 'krisbolton'
codepen:
dribbble: 
medium: '@krisbolton'
instagram:
pinterest:
linkedin: 'krisbolton'
producthunt:

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about.html
  - text: Contact
    url: /contact.html

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
